server:
  port: 8080
spring:
#  config:
#    activate:
#      on-profile: default
  data:
    mongodb:
      host: localhost #mongodb
      port: 27017
      database: ${MONGO_INITDB_ROOT_PASSWORD:task-manager-db}
#      username: root
#      password: admin
      authentication-database: admin
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html