apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
        - name: app
          image: juliosugaya/task-manager:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/task-manager-db
          imagePullPolicy: Always

# ... Deployment YAML definition
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: task-manager
spec:
  selector:
    app: task-manager
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer